
create or replace FUNCTION edwmgr.F_GET_MIF_VALUE_4_VC (MULTI_SRC_KEY_IN IN NUMBER)
   RETURN VARCHAR2
   DETERMINISTIC
IS
   MIF_VALUE   VARCHAR2(30);

   CURSOR GET_MIF_VALUE
   IS
      SELECT MULTI_SOURCE
        FROM WDT_MULTI_SOURCE
       WHERE MULTI_SOURCE_KEY = MULTI_SRC_KEY_IN;
BEGIN
   OPEN GET_MIF_VALUE;

   FETCH GET_MIF_VALUE INTO MIF_VALUE;

   IF GET_MIF_VALUE%NOTFOUND
   THEN
      MIF_VALUE := 'CCCS';
   END IF;

   CLOSE GET_MIF_VALUE;

   RETURN MIF_VALUE;
END;