/**** edwstg ****/
CREATE OR REPLACE PUBLIC SYNONYM "ZTT_EMPLOYEE_DEDN_INPUT" FOR "EDWSTG"."ZTT_EMPLOYEE_DEDN_INPUT";
CREATE OR REPLACE PUBLIC SYNONYM "ZTT_EMPLOYEE_DEDN_CLEAN" FOR "EDWSTG"."ZTT_EMPLOYEE_DEDN_CLEAN";
CREATE OR REPLACE PUBLIC SYNONYM "ZTT_EMPLOYEE_DEDN_WKEYS" FOR "EDWSTG"."ZTT_EMPLOYEE_DEDN_WKEYS";
CREATE OR REPLACE PUBLIC SYNONYM "ZTT_EMPLOYEE_DEDN_ERROR" FOR "EDWSTG"."ZTT_EMPLOYEE_DEDN_ERROR";
CREATE OR REPLACE PUBLIC SYNONYM "ZTT_EMPLOYEE_EARNING_INPUT" FOR "EDWSTG"."ZTT_EMPLOYEE_EARNING_INPUT";
CREATE OR REPLACE PUBLIC SYNONYM "ZTT_EMPLOYEE_EARNING_CLEAN" FOR "EDWSTG"."ZTT_EMPLOYEE_EARNING_CLEAN";
CREATE OR REPLACE PUBLIC SYNONYM "ZTT_EMPLOYEE_EARNING_WKEYS" FOR "EDWSTG"."ZTT_EMPLOYEE_EARNING_WKEYS";


/**** edwmgr ****/
CREATE OR REPLACE PUBLIC SYNONYM "ZFT_EMPLOYEE_DEDUCTION" FOR "EDWMGR"."ZFT_EMPLOYEE_DEDUCTION";
CREATE OR REPLACE PUBLIC SYNONYM "ZDT_DEDUCTION" FOR "EDWMGR"."ZDT_DEDUCTION";
CREATE OR REPLACE PUBLIC SYNONYM "ZFT_EMPLOYEE_EARNING" FOR "EDWMGR"."ZFT_EMPLOYEE_EARNING";
CREATE OR REPLACE PUBLIC SYNONYM "ZDT_EARNING" FOR "EDWMGR"."ZDT_EARNING";

