
  CREATE TABLE "EDWMGR"."ZFT_EMPLOYEE_DEDUCTION" 
   (	"MULTI_SOURCE_KEY" NUMBER NOT NULL ENABLE NOVALIDATE, 
	"TIME_KEY" NUMBER NOT NULL ENABLE NOVALIDATE, 
	"ADMINISTRATION_KEY" NUMBER NOT NULL ENABLE NOVALIDATE, 
	"DEMOGRAPHIC_KEY" NUMBER NOT NULL ENABLE NOVALIDATE, 
	"EMPLOYEE_KEY" NUMBER NOT NULL ENABLE NOVALIDATE, 
	"DEDUCTION_KEY" NUMBER NOT NULL ENABLE NOVALIDATE, 
	"PERSON_UID" NUMBER NOT NULL ENABLE NOVALIDATE, 
	"AGE" NUMBER, 
	"YEARS_OF_SERVICE" NUMBER, 
	"EMPLOYEE_DEDN_AMT" NUMBER, 
	"EMPLOYER_DEDN_AMT" NUMBER, 
	"SYSTEM_LOAD_PROCESS" VARCHAR2(30 BYTE) NOT NULL ENABLE NOVALIDATE, 
	"SYSTEM_LOAD_TMSTMP" DATE DEFAULT SYSDATE NOT NULL ENABLE NOVALIDATE, 
	"MIF_VALUE_VC" VARCHAR2(4000 BYTE) GENERATED ALWAYS AS ("EDWMGR"."F_GET_MIF_VALUE_4_VC"("MULTI_SOURCE_KEY")) VIRTUAL VISIBLE , 
	 CONSTRAINT "PK_WFT_EMPLOYEE_DEDN" PRIMARY KEY ("MULTI_SOURCE_KEY", "TIME_KEY", "ADMINISTRATION_KEY", "DEMOGRAPHIC_KEY", "EMPLOYEE_KEY", "DEDUCTION_KEY", "PERSON_UID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 163840 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDW_TBS"  ENABLE NOVALIDATE, 
	 CONSTRAINT "FK1_EMPLOYEE_DEDN" FOREIGN KEY ("MULTI_SOURCE_KEY")
	  REFERENCES "EDWMGR"."WDT_MULTI_SOURCE" ("MULTI_SOURCE_KEY") ENABLE NOVALIDATE, 
	 CONSTRAINT "FK2_EMPLOYEE_DEDN" FOREIGN KEY ("TIME_KEY")
	  REFERENCES "EDWMGR"."WDT_TIME" ("TIME_KEY") ENABLE NOVALIDATE, 
	 CONSTRAINT "FK3_EMPLOYEE_DEDN" FOREIGN KEY ("ADMINISTRATION_KEY")
	  REFERENCES "EDWMGR"."WDT_ADMINISTRATION" ("ADMINISTRATION_KEY") ENABLE NOVALIDATE, 
	 CONSTRAINT "FK4_EMPLOYEE_DEDN" FOREIGN KEY ("DEMOGRAPHIC_KEY")
	  REFERENCES "EDWMGR"."WDT_DEMOGRAPHIC" ("DEMOGRAPHIC_KEY") ENABLE NOVALIDATE, 
	 CONSTRAINT "FK5_EMPLOYEE_DEDN" FOREIGN KEY ("EMPLOYEE_KEY")
	  REFERENCES "EDWMGR"."WDT_EMPLOYEE" ("EMPLOYEE_KEY") ENABLE, 
	 CONSTRAINT "FK6_EMPLOYEE_DEDN" FOREIGN KEY ("DEDUCTION_KEY")
	  REFERENCES "EDWMGR"."ZDT_DEDUCTION" ("DEDUCTION_KEY") ENABLE NOVALIDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 163840 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDW_TBS" ;

  CREATE BITMAP INDEX "EDWMGR"."ZFT_EMPLOYEE_DEDUCTIN_INDEX_01" ON "EDWMGR"."ZFT_EMPLOYEE_DEDUCTION" ("MULTI_SOURCE_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 163840 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDW_TBS" ;

  CREATE BITMAP INDEX "EDWMGR"."ZFT_EMPLOYEE_DEDUCTIN_INDEX_03" ON "EDWMGR"."ZFT_EMPLOYEE_DEDUCTION" ("ADMINISTRATION_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 163840 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDW_TBS" ;

  CREATE BITMAP INDEX "EDWMGR"."ZFT_EMPLOYEE_DEDUCTIN_INDEX_04" ON "EDWMGR"."ZFT_EMPLOYEE_DEDUCTION" ("DEMOGRAPHIC_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 163840 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDW_TBS" ;

  CREATE BITMAP INDEX "EDWMGR"."ZFT_EMPLOYEE_INDEX_DEDUCTIN_05" ON "EDWMGR"."ZFT_EMPLOYEE_DEDUCTION" ("EMPLOYEE_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 163840 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EDW_TBS" ;
